///////////////////////////////////////////////////////////////////////////////
// TcPtpBestMasterDiagServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcPtpBestMasterDiag = 0x3F000000;
#define SRVNAME_TCPTPBESTMASTERDIAG "TcPtpBestMasterDiag"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TcPtpBestMasterDiagCTcPtpBestMasterDiagModule = {0xc7fbc673,0x1ab1,0x42e3,{0xbb,0xa5,0xb1,0x80,0x26,0x84,0x61,0xcc}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_TcPtpBestMasterDiagModulePTP = 0x00000002;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_579FD163_0940_4DB5_847B_D169483EF869_INCLUDED_)
#define _TC_TYPE_579FD163_0940_4DB5_847B_D169483EF869_INCLUDED_
enum UINTBOOL : USHORT {
	eFALSE = 0,
	eTRUE = 1
};
#endif // !defined(_TC_TYPE_579FD163_0940_4DB5_847B_D169483EF869_INCLUDED_)

#if !defined(_TC_TYPE_853A99B4_9052_4379_8D50_880189FB6D49_INCLUDED_)
#define _TC_TYPE_853A99B4_9052_4379_8D50_880189FB6D49_INCLUDED_
typedef BYTE TByteArray8[8];
#endif // !defined(_TC_TYPE_853A99B4_9052_4379_8D50_880189FB6D49_INCLUDED_)

#if !defined(_TC_TYPE_877CD04D_5D13_4B3B_92D2_0751D2423932_INCLUDED_)
#define _TC_TYPE_877CD04D_5D13_4B3B_92D2_0751D2423932_INCLUDED_
typedef BYTE TByteArray10[10];
#endif // !defined(_TC_TYPE_877CD04D_5D13_4B3B_92D2_0751D2423932_INCLUDED_)

#if !defined(_TC_TYPE_32E4F475_95C7_4D73_BF2E_4E45ACBD021F_INCLUDED_)
#define _TC_TYPE_32E4F475_95C7_4D73_BF2E_4E45ACBD021F_INCLUDED_
enum EPtpVersion : USHORT {
	PTPvDisabled = 0,
	PTPv1 = 1,
	PTPv2 = 2
};
#endif // !defined(_TC_TYPE_32E4F475_95C7_4D73_BF2E_4E45ACBD021F_INCLUDED_)

#if !defined(_TC_TYPE_6C49C8C2_D78F_4BC5_8DF9_289679FC62FE_INCLUDED_)
#define _TC_TYPE_6C49C8C2_D78F_4BC5_8DF9_289679FC62FE_INCLUDED_
enum EPtpState : USHORT {
	State_Inactive = 0,
	State_Initializing = 1,
	State_Faulty = 2,
	State_Disabled = 3,
	State_Listening = 4,
	State_Pre_Master = 5,
	State_Master = 6,
	State_Passive = 7,
	State_Uncalibrated = 8,
	State_Slave = 9,
	State_LinedelayOnly = 10
};
#endif // !defined(_TC_TYPE_6C49C8C2_D78F_4BC5_8DF9_289679FC62FE_INCLUDED_)

#if !defined(_TC_TYPE_A8B8B44C_F128_4CE2_AAEE_174CB03EC797_INCLUDED_)
#define _TC_TYPE_A8B8B44C_F128_4CE2_AAEE_174CB03EC797_INCLUDED_
#pragma pack(push,1)
typedef struct _TPtpDevInputs
{
	WORD Device_Status;
	AmsNetId AmsNetId;
	unsigned char Best_Master_Port;
} TPtpDevInputs, *PTPtpDevInputs;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_A8B8B44C_F128_4CE2_AAEE_174CB03EC797_INCLUDED_)

#if !defined(_TC_TYPE_176BB782_9B90_4346_9143_4974CB63BAF8_INCLUDED_)
#define _TC_TYPE_176BB782_9B90_4346_9143_4974CB63BAF8_INCLUDED_
typedef struct _TPtpDevDiag
{
	EPtpVersion PTP_Version;
	EPtpState PTP_State;
	unsigned char reserved1[4];
	TByteArray8 Clock_Identity;
	TByteArray10 Parent_Port_Identity;
	TByteArray8 Grandmaster_Clock_Identity;
	BYTE Grandmaster_Clock_Class;
	BYTE Grandmaster_Clock_Accuracy;
	USHORT Grandmaster_Clock_Variance;
	unsigned char reserved2[10];
	LONGLONG Offset_from_Master;
	ULONGLONG Mean_Path_Delay;
	unsigned char reserved3[64];
} TPtpDevDiag, *PTPtpDevDiag;
#endif // !defined(_TC_TYPE_176BB782_9B90_4346_9143_4974CB63BAF8_INCLUDED_)

#if !defined(_TC_TYPE_5EF85EF0_E51E_4A3E_91D0_B438E7B233B1_INCLUDED_)
#define _TC_TYPE_5EF85EF0_E51E_4A3E_91D0_B438E7B233B1_INCLUDED_
#pragma pack(push,1)
typedef struct _TPtpPortInputs
{
	unsigned char Ptp_State;
	USHORT Sync_Cycle_Counter;
	LONGLONG Offset_from_Master;
	LONGLONG TcToExtTimeOffset;
	SHORT Utc_Offset;
	UINTBOOL Utc_Offset_IsValid;
} TPtpPortInputs, *PTPtpPortInputs;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_5EF85EF0_E51E_4A3E_91D0_B438E7B233B1_INCLUDED_)

#if !defined(_TC_TYPE_FF060DD8_6328_43BD_9817_61B6C86AA52A_INCLUDED_)
#define _TC_TYPE_FF060DD8_6328_43BD_9817_61B6C86AA52A_INCLUDED_
typedef struct _TPtpPortDiag
{
	EPtpVersion PTP_Version;
	EPtpState PTP_State;
	enum : USHORT {
		Disabled = 0x00000000,
		Default_Profile = 0x00000020,
		TSN_Profile_802_1AS = 0x00000040,
		Power_Profile_C37_238_2011 = 0x00000080,
		Power_Profile_C37_238_2017 = 0x00000100
	} PTP_Protocol;
	enum : USHORT {
		NoLinkError = 0,
		LinkError = 1
	} PTP_Dev_State;
	TByteArray8 Clock_Identity;
	TByteArray10 Parent_Port_Identity;
	TByteArray8 Grandmaster_Clock_Identity;
	BYTE Grandmaster_Clock_Class;
	BYTE Grandmaster_Clock_Accuracy;
	USHORT Grandmaster_Clock_Variance;
	unsigned char reserved1[10];
	LONGLONG Offset_from_Master;
	ULONGLONG Mean_Path_Delay;
	USHORT Steps_removed;
	USHORT Sync_Event_Sequence_Number;
	enum : USHORT {
		ARB_arbitrary = 0,
		PTP_tai = 1
	} Timescale;
	SHORT Current_UTC_Offset;
	UINTBOOL Current_UTC_Offset_IsValid;
	UINTBOOL leap61;
	UINTBOOL Leap59;
	unsigned char reserved2[50];
	ULONG nSentPTPv2DelayReqMessages;
	ULONG nSentPTPv2DelayRespMessages;
	ULONG nSentPTPv2PDelayReqMessages;
	ULONG nSentPTPv2PDelayRespMessages;
	ULONG nSentPTPv2PDelayRespFollMessages;
	ULONG nSentPTPv2AnnounceMessages;
	ULONG nSentPTPv2SyncMessages;
	ULONG nSentPTPv2SyncFollowupMessages;
	ULONG nSentPTPv2BrokenMessages;
	ULONG nReceivedPTPv2DelayReqMessages;
	ULONG nReceivedPTPv2DelayRespMessages;
	ULONG nReceivedPTPv2PDelayReqMessages;
	ULONG nReceivedPTPv2PDelayRespMessages;
	ULONG nReceivedPTPv2PDelayRespFollMessages;
	ULONG nReceivedPTPv2AnnounceMessages;
	ULONG nReceivedPTPv2SyncMessages;
	ULONG nReceivedPTPv2SyncFollowupMessages;
	ULONG nReceivedPTPv2BrokenMessages;
	ULONG nProcessedPTPv2DelayReqMessages;
	ULONG nProcessedPTPv2DelayRespMessages;
	ULONG nProcessedPTPv2PDelayReqMessages;
	ULONG nProcessedPTPv2PDelayRespMessages;
	ULONG nProcessedPTPv2PDelayRespFollMessages;
	ULONG nProcessedPTPv2AnnounceMessages;
	ULONG nProcessedPTPv2SyncMessages;
	ULONG nProcessedPTPv2SyncFollowupMessages;
	unsigned char reserved3[24];
} TPtpPortDiag, *PTPtpPortDiag;
#endif // !defined(_TC_TYPE_FF060DD8_6328_43BD_9817_61B6C86AA52A_INCLUDED_)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
