///////////////////////////////////////////////////////////////////////////////
// TcPtpBestMasterDiagModule.h
#pragma once

#include "TcPtpBestMasterDiagInterfaces.h"

class CTcPtpBestMasterDiagModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CTcPtpBestMasterDiagModule();
	virtual	~CTcPtpBestMasterDiagModule();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	ITComObjectPtr m_spPTP;
///</AutoGeneratedContent>

	ITcADIPtr m_spADI;

	TPtpPortInputs* m_pBestMasterInputs;
	USHORT m_nBestMasterCycle;
	//TPtpPortInputs* m_pPort1Inputs;
	//USHORT m_nPort1Cycle;
	//TPtpPortInputs* m_pPort2Inputs;
	//USHORT m_nPort2Cycle;
	TPtpDevInputs* m_pDeviceInputs;

	TPtpPortDiag m_mBestMasterDiag;
	//TPtpPortDiag m_mPort1Diag;
	//TPtpPortDiag m_mPort2Diag;
};
