///////////////////////////////////////////////////////////////////////////////
// TcPtpBestMasterDiagClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TcPtpBestMasterDiagClassFactory.h"
#include "TcPtpBestMasterDiagServices.h"
#include "TcPtpBestMasterDiagVersion.h"
#include "TcPtpBestMasterDiagModule.h"

BEGIN_CLASS_MAP(CTcPtpBestMasterDiagClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_TcPtpBestMasterDiag, CID_TcPtpBestMasterDiagCTcPtpBestMasterDiagModule, SRVNAME_TCPTPBESTMASTERDIAG "!CTcPtpBestMasterDiagModule", CTcPtpBestMasterDiagModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTcPtpBestMasterDiagClassFactory::CTcPtpBestMasterDiagClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_TCPTPBESTMASTERDIAG));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(TcPtpBestMasterDiag));
#endif //defined(TCDBG_UNIT_VERSION)
}

