///////////////////////////////////////////////////////////////////////////////
// TcPtpBestMasterDiagInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "TcPtpBestMasterDiagServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
